### ISSUE TITLE
如何获取的 domjudge 公开接口？

### ISSUE THREAD

**Issue by mushan-zb** [StableAgOH/nxist-domjudge#1]
了解到对外一般都只会提供一个榜单地址，但不会提供 domjudge 的数据接口，想了解一下，是怎么通过 api 获取到的。我是 https://rl.algoux.org/ 平台的维护者，想要了解一下 api，能更好的支持榜单的获取

**Comment by StableAgOH** [comment]
默认情况下 users, event-feed 等 API 是不公开的（需要 HTTP 身份认证），但 submissons, organizations, teams 等 API 都是公开的，这就是本项目数据的来源。

具体请参阅 [DOMjudge 官方文档](https://www.domjudge.org/documentation)下的 API documentation 小节。
